#!/bin/bash
echo "
                    /   \              /`\       _
\_..           /`.,/     \_         .,`   \     / \_
    \         /            \      _/       \_  /    \     _
     \__,.   /              \    /           \/.,   _|  _/ \
          \_/                \  /;,.,;;\      \_ \_/  \/    \
                           _  \/   /     ,../;,.\    _/      \
             /           _/m\  \  /    |         \  /.,/.\   _\
           _/           /MMmm\  \_     |          \/      \_/  \
          /      \     |MMMMmm|   \__   \          \_       \   \_
                  \   /MMMMMMm|      \   \           \       \    \
                   \  |MMMMMMmm\      \___            \_      \_   \
                    \|MMMMMMMMmm|____.;  /\_            \       \   \_
                    /`.,___________...,,;   \            \   \        \
                   /       \          |      \    |__     \   \_       \
                 _/        |           \      \_     \     \    \       \_
                /                               \     \     \_   \        \
                                                 \     \      \   \__      \
                                                  \     \_     \     \      \
                                                   |      \     \     \      \
                                                   \ms          |            \ "
                                                   
# Test if they have a torch, if they dont, display this text                                                 
echo "Cave is completely pitch black."
echo "Maybe it's better to return when you have obtain a light source."

# The player will not be able to enter the cave until they have a torch (to create a torch they need a "sturdy branch" and "fire")
