#!/bin/bash

echo "What do you want to make?"
read -p The chpices are:
  1. Fire
  2. Torch
  3. Spear  decision
case "$decision" in

1)
if grep -q "Branch" Inventory; [ $? -eq 0 ] && if grep -q "Branch2" Inventory; [ $? -eq 0 ] && if grep -q "Branch3" Inventory; [ $? -eq 0 ]
#Test if they have branch && branch2 && branch 3, if they do
then
echo "You used 3 branches to create a fire."
echo "Fire" >Inventory
#add smth here to rm the branches from their inventory
else
echo "You're missing some items need to create a fire."
fi
;;
2)
#Test if they have a sturdy branch && a fire, if they do
if grep -q "Sturdy" Inventory; [ $? -eq 0 ] && if grep -q "Fire" Inventory; [ $? -eq 0 ]
then
echo "You used a sturdy branch and fire to make a torch."
echo "Torch" > Inventory
#add smth here to rm the branch from inv
else
echo "You're missing some items needed to create a fire"
fi
;;
3)
if grep -q "Sturdy" Inventory; [ $? -eq 0 ] && if grep -q "Knife" Inventory; [ $? -eq 0 ]
#test if they have sturdy branch && pocket knife, if they do
then
echo "You used a sturdy branch and your pocket knife to make a spear" 
echo "Spear" > Inventory
#add smth here to rm the branch from inv
else
echo "You're missing some items needed to create a spear."
fi
;;
*) 
echo "Please enter one of the numbers" 
;;
esac
