#!/bin/bash

echo "What do you want to make?"
read -p echo "
  1. Fire
  2. Torch
  3. Spear " decision
case "$decision" in

1)
#Test if they have branch && branch2 && branch 3, if they do
echo "You used 3 branches to create a fire."
echo "Fire" >Inventory
#else
echo You're missing some items need to create a fire."
;;
2)
#Test if they have a sturdy branch && a fire, if they do
echo "You used a sturdy branch and fire to make a torch."
echo "Torch" > Inventory
#else
echo "You're missing some items needed to create a fire"
3)
#test if they have sturdy branch && pocket knife, if they do
echo "You used a sturdy branch and your pocket knife to make a spear" 
echo "Spear" > Inventory
#else 
echo "You're missing some items needed to create a spear."
