#!/bin/bash

if echo Inventory | grep Knife | echo $? == 1; # Checks if the pocket Knife is already in Inventory 
then #If the pocket knife is NOT already in the inventory, this plays
  echo "This is your luggage."
  echo "Maybe there could be something useful in here?"
  read -p "Do you want to open your luggage? y/n  " choice
  case "$choice" in
  n|no|No|N)
  echo "You dont open the luggage"
  ;;
  y|yes|Yes|Y)
  echo "You open your luggage. You find a pocket knife."
  echo "A pocket knife is added to your inventory."
  echo "Pocket Knife " > Inventory
  ;;
  esac
else #If the pocket knife is already in inventory, this plays 
   echo "The Luggage is empty" 
fi

