#!/bin/bash

if echo Inventory | grep Knife | echo $? == 1; ##Checks if the pocket Knife is already in Inventory 
then
  echo "This is your luggage."
  echo "Maybe there could be something useful in here?"
  read -p "Do you want to open your luggage? y/n  " choice
  case "$choice" in
  n|no)
  echo "You dont open the luggage"
  ;;
  y|yes|Yes|y)
  echo "You open your luggage. You find a pocket knife."
  echo "A pocket knife is added to your inventory."
  echo "Pocket Knife " > Inventory
  ;;
  esac
else
   echo "The Luggage is empty" 
fi

