#!/bin/bash


#Test if this is the first time they've talked, if it is display this.... 
i=0 
while [ $i -eq 0 ]
do
echo "
        _.---._
     .- ((O))  -.
      \ _.\_/._ /
       /..___..\
       ;-.___.-;
      (| e ) e |)     ()()
       \  /_   /      ||||
       _\__-__/_    (\|'-|
     /` / \V/ \ `\   \ )/
    /   \  Y  /   \  /=/
   /  |  \ | / {}  \/ /
  /  /|   \|.   |\   /
  \  \|    |.   | \_/
   \ /\    |.   |
    \_/\   |.   |
    /)_/   |    |  "

echo "So you're awake... "
echo "You must be distressed but worry not!" 
echo "We were struck by lighting and one of the plane's wings was hit. Causing us to crash!!"
echo "I've taken the liberty of looking around a but, it seems this island is completely deserted." 
echo " Thats right! HO HO HO! We are STRANDED!" 
echo "We need to find a way off this island but, lets start with finding something to eat."
echo "I suggest starting with looking the forest."
echo "Should you need any assistance I'll be here" 
i=$(( $i + 1 ))
done

#case 





